config/routes.rb
LatinFoods::Application.routes.draw do

  get "videos/index"
  

  devise_for :users
  devise_scope :users do
     get '/users/sign_out' => 'devise/sessions#destroy'
  end

  match '/home/save_details/#{}', :to => 'home#save_details'
  match '/devise/home/contact', :to => 'home#contact'

  resources :statistics
  resources :roles
  resources :users_admin
  resources :reports do
    member do
      get 'generatereport'
    end
  end
  resources :videos do
    member do
      post :add_comment
      get :removevideo
    end     
    new do
       post :upload
       get  :save_video
     end
  end

  match "videos/:id/add_comment", :to => "videos#add_comment"

  
  

   root :to => 'home#index'

   match ':controller(/:action(/:id))(.:format)'
end

app/models/video.rb
class Video < ActiveRecord::Base
  
  attr_accessible :title, :description, :yt_video_id, :is_complete
  validates :title, :description, presence: true
  attr_accessor :comment
  
  scope :completes,   where(:is_complete => true)
  scope :incompletes, where(:is_complete => false)
  
  def create_comment(comment)
    begin
      comments.create(:comment => comment)
      Video.yt_session.add_comment(yt_video_id, comment)
    rescue
      false
    end
  end
  
    
  def self.yt_session
    @yt_session ||= YouTubeIt::Client.new(:username => YouTubeITConfig.username , :password => YouTubeITConfig.password , :dev_key => YouTubeITConfig.dev_key)    
  end

  def self.delete_video(video)
    yt_session.video_delete(video.yt_video_id)
    video.destroy
      rescue
        video.destroy
  end

  def self.update_video(video, params)
    yt_session.video_update(video.yt_video_id, video_options(params))
    video.update_attributes(params)
  end

  def self.token_form(params, nexturl)
    yt_session.upload_token(video_options(params), nexturl)
  end

  def self.delete_incomplete_videos
    self.incompletes.map{|r| r.destroy}
  end

  private
    def self.video_options(params)
      opts = {:title => params[:title],
             :description => params[:description],
             :category => "People",
             :keywords => ["test"]}
      params[:is_unpublished] == "1" ? opts.merge(:private => "true") : opts
    end
end

app/controllers/videos_controller.rb
class VideosController < InheritedResources::Base

def index
  @videos = Video.paginate(:per_page => 10, :page => params[:page]).order('created_at DESC')
end

def upload
  @video = Video.new(params[:video])
  if @video.save
    @upload_info = Video.token_form(params[:video], save_video_new_video_url(:video_id => @video.id))
  else
    respond_to do |format|
      flash[:notice] = 'Please fill title and description'
      format.html { render "/videos/new" }
    end
  end
end

  def update
    @video     = Video.find(params[:id])
    @result    = Video.update_video(@video, params[:video])
    respond_to do |format|
      format.html do
        if @result
          redirect_to @video, :notice => "video successfully updated"
        else

          respond_to do |format|
            flash[:notice] = 'Please fill title nad description'
            format.html { redirect_to edit_video_path(@video) }
          end
        end
      end
    end
  end

  def save_video
    @video = Video.find(params[:video_id])
    if params[:status].to_i == 200
      @video.update_attributes(:yt_video_id => params[:id].to_s, :is_complete => true)
      Video.delete_incomplete_videos
    else
      Video.delete_video(@video)
    end
    redirect_to videos_path, :notice => "video successfully uploaded"
  end

  def destroy
    @video = Video.find(params[:id])
    if Video.delete_video(@video)
      flash[:notice] = "video successfully deleted"
    else
      flash[:error] = "video unsuccessfully deleted"
    end
    redirect_to videos_path
  end

  def add_comment
    @video = Video.find(params[:id])
    @comment = @video.comments.new
    @comment.comment = params[:video][:comment]
    @comment.user_id = current_user.id
    @comment.commentable_type="video"
    if @comment.save!
      flash[:notice] = "Comment has been sucessfully added."
    else
      flash[:error] = "Sorry the comment has not been added."
    end
    redirect_to @video    
  end

  def removevideo
    @video = Video.find(params[:id])
    @video.destroy
    respond_to do |format|
      format.html{ redirect_to(action: 'index', controller: 'videos') }
    end
  end


  protected
    def collection
      @videos ||= end_of_association_chain.completes
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
  <div class="form-group">
  <label class="control-label col-md-2">
    <%= f.label :title,  :default => "Title" %>
    </label>
    <div class="col-md-6">
    <%= f.text_field :title, :require => true, :class => 'text_field', class: 'form-control'%>
    </div>
    
  </div>

  <div class="form-group">
  <label class="control-label col-md-2">
    <%= f.label :description %>
    </label>
    <div class="col-md-6">
    <%= f.text_area :description, :require => true , class: 'form-control', rows: "7" %>
    </div>
  </div>

<div class="form-group">
  <div class="col-md-offset-3">
<% if @video.new_record?%>
   <button class="btn btn-primary" type="submit">
     <%= t("web-app-theme.save", :default => "Step 2") %>
  </button>
<%else%>
  <button class="btn btn-primary" type="submit">
     <%= t("web-app-theme.save", :default => "Save") %>
  </button>
<%end%>

  
	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), videos_path, :class => "btn btn-warning" %>
</div>
</div>

app/views/videos/edit.html.erb
<div class="container">
    <div class="row">
      <%= render partial: '/sidebar' %>

      <div class="col-md-9">

        <div class="row well">

        <% if flash[:notice]  %>
          <div class="alert alert-dismissable alert-warning">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <strong><%= flash[:notice] %></strong> 
          </div>
        <% end %>
              <p class="lead">Edit Video</p>
    <%= form_for @video, :url => video_path(@video), :html => { :class => 'form-horizontal'} do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/videos/index.html.erb
<div class="container">
  <div class="row">
    <%= render partial: '/sidebar' %>
    <div class="col-md-9" id="padding">
      <div class="row">
        <div class="col-md-10">
        <% if flash[:notice]  %>
          <div class="alert alert-dismissable alert-success">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <strong><%= flash[:notice] %></strong> 
          </div>
        <% end %>
          <p class="lead"> Listing videos </p>
        </div>
        <div class="col-md-2">
          <%= link_to 'Add Video', upload_new_video_path, class: 'btn btn-primary' %>
        </div>
        </div>


  <table class="table table-striped table-hover">
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>

    <% @videos.each do |video| %>
      <tr>
        <td><%= video.title %></td>
        <td><%= link_to 'Show', video_path(video.id) %></td>
        <td><%= link_to 'Edit', edit_video_path(video.id) %></td>
        <td> <%= link_to 'Destroy',{action: 'destroy', controller: 'videos', id: video.id}, method: :delete, data: { confirm: 'Are you sure?' }%></td>
      </tr>
    <% end %>
  </table>
  <div  class='col-lg-offset-4'>
    <%= will_paginate(@videos) %>
  </div>
    

app/views/videos/new.html.erb
<div class="container">
  <div class="row">
    <%= render partial: '/sidebar' %>
    <div class="col-md-9">
      <div class="row  well">
      <% if flash[:notice]  %>
          <div class="alert alert-dismissable alert-warning">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <strong><%= flash[:notice] %></strong> 
          </div>
        <% end %>
        <p class="lead">  Add Video </p>
        <p class="lead">Step 1: add information about your video.</p>
        <%= form_for @video, :url => upload_new_video_path, :html => { :class => 'form-horizontal', validation: true } do |f| %>
          <%= render :partial => "form", :locals => {:f => f} %>
          <% end %>
      </div>
    </div>
  </div>
</div>






             
    
   

app/views/videos/show.html.erb
<div class="container">
  <div class="row">
    <%= render partial: '/sidebar' %>
      <div class="col-md-9">
      <div class="row">
        <% flash.each do |type, message| -%>
         <div class="alert alert-dismissable alert-success">
         <button type="button" class="close" data-dismiss="alert">×</button>
            <strong><%= message %></strong> 
          </div>
        <% end %>
      </div>
        <div class="row">   
         <p id="padding">
          <%= raw yt_client.my_video(@video.yt_video_id).embed_html %>
        </p>
        <h3><%= @video.description %></h3>
        <p><b>url:</b> <a href="http://www.youtube.com/watch?v=<%= @video.yt_video_id %>&feature=youtube_it" target="_blank">http://www.youtube.com/watch?v=<%= @video.yt_video_id %></a></p>

      <div class="form-group">
      <%= link_to  'Edit',edit_video_path(@video), class: 'btn btn-primary' %>
       <%= link_to 'Destroy',{action: 'destroy', controller: 'videos', id: @video.id}, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary'%>
        <%= link_to  'Back', videos_index_path, class: 'btn btn-primary' %>
      </div>      
    
  
  

app/views/videos/upload.html.erb
<div class="container">
  <div class="row">
    <%= render partial: '/sidebar' %>
    <div class="col-md-9">
      <div class="row well">
        <p class="lead">Step 2: upload a new video.</p>
        <%= form_tag @upload_info[:url], :multipart => true do %>
          <%= hidden_field_tag :token, @upload_info[:token] %>
          <%= label_tag :file %>
          <%= file_field_tag :file%></br>
          <%= submit_tag "Upload video", class: 'btn btn-primary'%>
          <%= link_to  'Cancel',  removevideo_video_path(@video.id), class: 'btn btn-primary' %>
        <% end %>    
      </div>
    </div>
  </div>
</div>