config/routes.rb
LatinFoods::Application.routes.draw do

  get "videos/index"
  

  devise_for :users
  devise_scope :users do
     get '/users/sign_out' => 'devise/sessions#destroy'
  end

  match '/home/save_details/#{}', :to => 'home#save_details'
  match '/devise/home/contact', :to => 'home#contact'

  resources :statistics
  resources :roles
  resources :users_admin
  resources :reports do
    member do
      get 'generatereport'
    end
  end
  resources :videos do
    member do
      post :add_comment
      get :removevideo
    end     
    new do
       post :upload
       get  :save_video
     end
  end

  match "videos/:id/add_comment", :to => "videos#add_comment"

  
  

   root :to => 'home#index'

   match ':controller(/:action(/:id))(.:format)'
end

app/controllers/users_admin_controller.rb
class UsersAdminController < ApplicationController
	before_filter :authenticate_user!

	def index
		@users = User.paginate(:per_page => 10, :page => params[:page]).order('created_at DESC')
	end

	def show
    @user = User.find(params[:id])
  end

	def new
		@user = User.new
	end

	def edit
    @user = User.find(params[:id])
  end

	def create
		@user = User.new
		@user.first_name = params[:user][:first_name]
		@user.last_name = params[:user][:last_name]
		@user.email = params[:user][:email]
		@user.institution = params[:user][:institution]
		@user.password = params[:user][:password]
		@user.password_confirmation = params[:user][:password_confirmation]
		respond_to do |format|
			if @user.save
		    @user.add_role params[:user][:role]
		    format.html { redirect_to users_admin_index_path }
		    flash[:notice] =  'User successfully created.' 
			else
	    	format.html {render action: 'new'}
			end
		end
	end

  def update
    @user = User.find(params[:id])
    @user.first_name = params[:user][:first_name] if (params[:user][:first_name].length != 0)
    @user.last_name = params[:user][:last_name] if (params[:user][:last_name].length != 0)
		@user.institution = params[:user][:institution] if (params[:user][:institution].length != 0)
		@user.email = params[:user][:email] if (params[:user][:email].length != 0)
		@user.password = params[:user][:password] if !params[:user][:password].length !=0
		@user.password_confirmation = params[:user][:password_confirmation] if !params[:user][:password_confirmation].length != 0
		respond_to do |format|
		  if @user.save
	    	@user.roles.clear
	    	@user.add_role params[:user][:role]
		    format.html { redirect_to users_admin_path } 
		    flash[:notice] =  'User was successfully updated.' 
		  else
		    format.html {render action: 'edit'}
		  end
	  end
	end

	def destroy
	  @user = User.find(params[:id])
	  @user.roles.clear
	  @user.destroy
	  @users = User.paginate(:per_page => 10, :page => params[:page]).order('created_at DESC')

	  respond_to do |format|
	    format.js
	    format.html { redirect_to users_admin_index_path }
	    format.json { head :no_content }
	  end
	end
end

app/helpers/users_admin_helper.rb
module UsersAdminHelper
end

app/views/users_admin/_form.html.erb
<fieldset>
<div class="form-horizontal">
<%= form_for(@user, url: @url) do |f| %>
  <% if @user.errors.any? %>  
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li class="alert alert-danger"><%= msg %></li>
    <% end %>
    </ul>
  <% end %>

  <div class="form-group">
    <%= f.label "First_name", class: 'col-md-2 control-label'%>
    <div class="col-md-6">
      <%= f.text_field :first_name, class: 'form-control input-md', required: true %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label "Last Name", class: 'col-md-2 control-label'  %>
    <div class="col-md-6">
      <%= f.text_field :last_name, class: 'form-control input-md', required: true %>
      </div>
  </div>

   <div class="form-group">
    <%= f.label "Institution", class: 'col-md-2 control-label'  %>
     <div class="col-md-6">
    <%= f.text_field :institution, class: 'form-control input-md', required: true %>
    </div>
  </div>

   <div class="form-group">
    <%= f.label "Email", class: 'col-md-2 control-label'  %>
    <div class="col-md-6">
    <%= f.text_field :email, class: 'form-control input-md', required: true %>
  </div>
  </div>

  <div class="form-group">
    <%= f.label "Password", class: 'col-md-2 control-label'  %>
    <div class="col-md-6">
    <%= f.password_field :password, class: 'form-control input-md' %>
  </div>
  </div>

  <div class="form-group">
    <%= f.label "Password Confirmation", class: 'col-md-2 control-label'  %>
    <div class="col-md-6">
    <%= f.password_field :password_confirmation, class: 'form-control input-md' %>
  </div>
  </div>

  <div class="form-group">
  <label class="col-md-2 control-label">Role</label>
  <div class="col-md-4">
    <%= f.select :role, Role.all.collect {|p| [ p.name] },{:default => 'Guest'}, { :class => 'form-control'} %>
  </div>
</div>

  <div class="form-group">
  <div class="col-md-offset-2 col-md-8">
   <%= f.submit "Submit", class: 'btn btn-success' %>
   <%= link_to 'Back', users_admin_index_path, class: 'btn btn-default' %>
  </div>
</div>

</fieldset>

 
<% end %>
</div>
</fieldset>

app/views/users_admin/edit.html.erb
<div class="container">
  <div class="row">
    <%= render partial: '/sidebar' %>
    <div class="col-md-9">
    <div class="well">
    <% @url = {controller: 'users_admin', action: 'update', method: :put} %>
      <legend>Edit <%= @user.first_name %> details </legend>
      <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/users_admin/index.html.erb
<div class="container">
	<div class="row">
		<%= render partial: '/sidebar' %>
		<div class="col-md-9" id="padding">
			<div class="row">
        <div class="col-md-10">
        <% if flash[:notice]  %>
          <div class="alert alert-dismissable alert-success">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <strong><%= flash[:notice] %></strong> 
          </div>
        <% end %>
          <p class="lead"> Listing users </p>
        </div>
        <div class="col-md-2">
          <%= link_to 'Add User', new_users_admin_path, class: 'btn btn-primary' %>
        </div>
        </div>


  <table class="table table-striped table-hover">
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Institution</th>
      <th>Role</th>
      <th colspan="3" class="text-center"></th>
    </tr>

    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.institution %></td>
        <td><%= user.roles.first.name %></td>
        <td><%= link_to 'Show', users_admin_path(user) %></td>
        <td><%= link_to 'Edit', edit_users_admin_path(user) %></td>
        <td><%= link_to 'Destroy',users_admin_path(user), method: :delete, data: { confirm: 'Are you sure?' }%></td>
      </tr>
    <% end %>
  </table>
  <div  class='col-lg-offset-4'>
    <%= will_paginate(@users, :renderer => WillPaginate::ActionView::LinkRenderer)%>
  </div>
    
  	</div>
</div>

app/views/users_admin/new.html.erb
<div class="container">
  <div class="row">
    <%= render partial: '/sidebar' %>
    <div class="col-md-9">
    <div class="well">
     <% @url = {controller: 'users_admin', action: 'create', method: :post} %>
     <%= notice %>
     <legend>User registration Form </legend>
      <%= render 'form' %>
    </div>
    </div>
  </div>
</div>

app/views/users_admin/show.html.erb
<div class="container">
	<div class="row">
		<%= render partial: '/sidebar' %>
		<div class="col-md-9">
		<div class="well">
		  <b>Name:</b>
		  	<%= @user.first_name << @user.last_name %>
			</p>

		<p>
		  <b>Email:</b>
		  <%= @user.email %>
		</p>

		<p>
		  <b>Institution:</b>
		  <%= @user.institution %>
		</p>

		<%= link_to 'Edit', edit_users_admin_path(@user), class: 'btn btn-success' %>
		<%= link_to 'Back',  users_admin_index_path, class: 'btn btn-default' %>

		</div>
	</div>
	</div>
</div>