config/routes.rb
LatinFoods::Application.routes.draw do

  get "videos/index"
  

  devise_for :users
  devise_scope :users do
     get '/users/sign_out' => 'devise/sessions#destroy'
  end

  match '/home/save_details/#{}', :to => 'home#save_details'
  match '/devise/home/contact', :to => 'home#contact'

  resources :statistics
  resources :roles
  resources :users_admin
  resources :reports do
    member do
      get 'generatereport'
    end
  end
  resources :videos do
    member do
      post :add_comment
      get :removevideo
    end     
    new do
       post :upload
       get  :save_video
     end
  end

  match "videos/:id/add_comment", :to => "videos#add_comment"

  
  

   root :to => 'home#index'

   match ':controller(/:action(/:id))(.:format)'
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  attr_accessible :name
  scopify
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
	before_filter :authenticate_user!

	def index
		@roles = Role.paginate(:per_page => 10, :page => params[:page]).order('created_at DESC')
	end

	def show
    @role = Role.find(params[:id])
  end

	def new
		@role = Role.new
		@url = {controller: 'roles', action: 'create', method: :post}
	end

	def edit
    @role = Role.find(params[:id])
    @url = {controller: 'roles', action: 'update', method: :put}
  end

	def create
		
		@role = Role.new(params[:role])
		temp = false
		Role.all.each do |rolename|
			if rolename.name == params[:role][:name]
				temp = true
				break
			end
		end
		respond_to do |format|
	  	if (temp == false)  &&  @role.save
	    	format.html { redirect_to roles_path }
	    	flash[:notice] = 'Role successfully created.'
	  	else
	    	format.html { render action: "new" }
	    	flash[:notice] = 'Role already exist'
	  	end
		end
	end


  def update
  	temp = false
		Role.all.each do |rolename|
			if rolename.name == params[:role][:name]
				temp = true
				break
			end
		end
    @role = Role.find(params[:id])
		respond_to do |format|
		  if (temp == false) && @role.update_attributes(params[:role])
		    format.html { redirect_to roles_path }
		    flash[:notice] = 'Role successfully updated.' 
		  else
		    format.html { render action: "edit" }
		    flash[:notice] = 'Role already exist'
		  end
    end
  end

	def destroy
		temp = true
	  @role = Role.find(params[:id])
	  User.all.each do |user|
	  	if user.roles.first.id == @role.id
	  		temp = false
	  		break
	  	end
	  end 
		respond_to do |format|
		  if temp 
		  	flash[:notice] = "Can't delete role Which is already assigned."
		  	@roles = Role.paginate(:per_page => 10, :page => params[:page]).order('created_at DESC')
		    format.html { redirect_to roles_path }
		  else
		  	@role.destroy
		  	@roles = Role.paginate(:per_page => 10, :page => params[:page]).order('created_at DESC')
		  	flash[:notice] = 'Role successfully deleted.' 
		    format.html { redirect_to roles_path }
		  end
	  end
	end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<fieldset>
<div class="form-horizontal">
<%= form_for(@role, url: @url) do |f| %>

  <% if @role.errors.any? %>
    
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |msg| %>
        <li class="alert alert-danger"><%= msg %></li>
      <% end %>
      </ul>
  <% end %>
 <% if flash[:notice]  %>
          <div class="alert alert-dismissable alert-success">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <strong><%= flash[:notice] %></strong> 
          </div>
        <% end %>


  <div class="form-group">
    <%= f.label "Name", class: 'col-md-2 control-label'%>
    <div class="col-md-6">
      <%= f.text_field :name, class: 'form-control input-md' %>
    </div>
  </div>
  

</div>
  <div class="form-group">
  <div class="col-md-offset-2 col-md-8">
   <%= f.submit "Submit", class: 'btn btn-success' %>
   <%= link_to 'Back', roles_path, class: 'btn btn-default' %>
  </div>
</div>

</fieldset>

 
<% end %>
</div>
</fieldset>

app/views/roles/edit.html.erb
<div class="container">
  <div class="row">
    <%= render partial: '/sidebar' %>
    <div class="col-md-9">
    <div class="well">
    <% @url = {controller: 'roles', action: 'update', method: :put} %>
      <legend>Edit <%= @role.name %> role </legend>
      <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/roles/index.html.erb
<div class="container">
	<div class="row">
		<%= render partial: '/sidebar' %>
		<div class="col-md-9" id="padding">
      <div class="row">
        <div class="col-md-10">
			     <p class="lead">Listing roles</p>
            <% if flash[:notice]  %>
              <div class="alert alert-dismissable alert-success">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <strong><%= flash[:notice] %></strong> 
              </div>
            <% end %>
      </div>
    <div class=" col-md-2">
      <%= link_to 'Add Role', new_role_path, class: 'btn btn-primary' %>
    </div>
  </div>
  <table class="table table-striped table-hover">
    <tr>
      <th>ID</th>
      <th>Role</th>
      <th colspan="3" class="text-center"></th>
    </tr>

  <% @roles.each do |role| %>
    <tr>
      <td><%= role.id %></td>
      <td><%= role.name %></td>

      <td><%= link_to 'Edit', edit_role_path(role) %></td>
      <td><%= link_to 'Destroy',role_path(role), method: :delete, data: { confirm: 'Are you sure?' }%></td>
    </tr>
  <% end %>
  </table>
		</div>
	</div>
  <div  class='col-lg-offset-4'>
    <%= will_paginate(@roles, :renderer => WillPaginate::ActionView::LinkRenderer)%>
  </div>
</div>

app/views/roles/new.html.erb
<div class="container">
  <div class="row">
    <%= render partial: '/sidebar' %>
    <div class="col-md-9">
    	<div class="well">
     <% @url = {controller: 'roles', action: 'create', method: :post} %>
      <legend>Add Role </legend>
      <%= render 'form' %>
    </div>
    </div>
  </div>
</div>